### ISSUE TITLE
Перестало работать

### ISSUE THREAD

**Issue by Azat868** [blackcofee/rublock-tor#2]
Добрый день
Подскажите с чего начать поиски , где какие логи почитать. 
Установил все по инструкции , работало ровно два дня, потом сайты стали  открываться напрямую. 
Все что пришло на ум это: /opt/etc/init.d/S33tor check , там пишет все норм alive. 
В syslog почитал, ничего связанного с тор и его проблемами не обнаружил

**Comment by Azat868** [comment]
Оказывается метод не работает только для клиентов vpn. То есть подключенные к роутеру на прошивке  padavan , не могут открывать onion и трафик от забл сайтов не перенаправляется через тор. Нагуглил интересный моменты:

mcedit /opt/etc/tor/torrc
#TransPort 10.8.5.1:9040 # Нужно только для работы через VPN

Но мне не помогло.

**Comment by Azat868** [comment]
netstat -ltupn

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 10.8.0.1:9040           0.0.0.0:*               LISTEN      674/tor
tcp        0      0 192.168.1.1:9040        0.0.0.0:*               LISTEN      674/tor
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      491/dnsmasq
tcp        0      0 192.168.1.1:53          0.0.0.0:*               LISTEN      491/dnsmasq
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      674/tor
tcp        0      0 127.0.0.1:65053         0.0.0.0:*               LISTEN      661/dnscrypt-proxy
udp        0      0 127.0.0.1:65053         0.0.0.0:*                           661/dnscrypt-proxy
udp        0      0 127.0.0.1:53            0.0.0.0:*                           491/dnsmasq
udp        0      0 192.168.1.1:53          0.0.0.0:*                           491/dnsmasq
udp        0      0 0.0.0.0:57655           0.0.0.0:*                           661/dnscrypt-proxy
udp        0      0 0.0.0.0:67              0.0.0.0:*                           491/dnsmasq
udp        0      0 127.0.0.1:9053          0.0.0.0:*                           674/tor

**Comment by blackcofee** [comment]
mcedit /opt/etc/tor/torrc
Убираем 
TransListenAddress 127.0.0.1
TransListenAddress 192.168.1.1 #адрес LAN интерфейса
Правим 
TransPort 192.168.1.1:9040
на 
0.0.0.0:9140

mcedit /etc/storage/post_iptables_script.sh
Добавляем
/bin/iptables -t nat -I PREROUTING -i tun1 -p tcp -m set --match-set rublack-dns dst -j REDIRECT --to-ports 9040
/bin/iptables -t nat -I PREROUTING -i tun1 -p tcp -m set --match-set rublack-ip dst -j REDIRECT --to-ports 9040
/bin/iptables -t nat -I PREROUTING -i ppp+ -p tcp -m set --match-set rublack-dns dst -j REDIRECT --to-ports 9040
/bin/iptables -t nat -I PREROUTING -i ppp+ -p tcp -m set --match-set rublack-ip dst -j REDIRECT --to-ports 9040

**Comment by Azat868** [comment]
**mcedit /opt/etc/tor/torrc**
```bash
User admin
PidFile /opt/var/run/tor.pid
DataDirectory /opt/var/lib/tor
ExcludeExitNodes {RU},{UA},{AM},{KG}
VirtualAddrNetwork 10.254.0.0/16 # виртуальные адреса для .onion ресурсов
AutomapHostsOnResolve 1
TransPort 0.0.0.0:9040
Transport 10.5.0.1:9040

DNSPort 9053
DNSListenAddress 127.0.0.1
```




**mcedit /etc/storage/post_iptables_script.sh**
```bash
#!/bin/sh

### Custom user script
### Called after internal iptables reconfig (firewall update)

/etc/storage/tg_say.sh Правила брандмауэра обновлены.

iptables -t nat -I PREROUTING -i br0 -p tcp -m set --match-set rublack-dns dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i br0 -p tcp -m set --match-set rublack-ip dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i br0 -p tcp -m set --match-set onion dst -j REDIRECT --to-ports 9040

iptables -t nat -I PREROUTING -i tun1 -p tcp -m set --match-set rublack-dns dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i tun1 -p tcp -m set --match-set rublack-ip dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i tun1 -p tcp -m set --match-set onion dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i ppp+ -p tcp -m set --match-set rublack-dns dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i ppp+ -p tcp -m set --match-set rublack-ip dst -j REDIRECT --to-ports 9040
iptables -t nat -I PREROUTING -i ppp+ -p tcp -m set --match-set onion dst -j REDIRECT --to-ports 9040
```

**Comment by Azat868** [comment]
Привел к такому виду эти два файла. Потом ребутнул. В итоге, заглушка роскомнадзора не показывается, в браузере просто пишет не удалось открыть сайт.
Открыв **netstat -ltupn** увидел что tor  вообще не слушает ни один адрес и порт.
Чекнул:
```bash
/opt/home/admin # /opt/etc/init.d/S33tor check
 Checking tor...              dead. 
/opt/home/admin # /opt/etc/init.d/S33tor start
 Starting tor...              done. 
/opt/home/admin # /opt/etc/init.d/S33tor check
 Checking tor...              dead. 
```
Как видно после старта сразу умирает. 
Пытался найти логи но безуспешно, где они все таки находятся?
```bash
/opt/home/admin # find / -name "tor" -print
/media/Main/opt/sbin/tor
/media/Main/opt/share/tor
/media/Main/opt/var/lib/tor
/media/Main/opt/etc/tor
/media/Main/opt/lib/upgrade/keep.d/tor
/opt/sbin/tor
/opt/share/tor
/opt/var/lib/tor
/opt/etc/tor
/opt/lib/upgrade/keep.d/tor
/opt/home/admin # ls /media/Main/opt/sbin/tor
/media/Main/opt/sbin/tor
/opt/home/admin # ls /opt/sbin/tor
/opt/sbin/tor
/opt/home/admin # ls /opt/share/tor
geoip   geoip6
/opt/home/admin # ls /opt/var/lib/tor
cached-certs                cached-microdescs           lock
cached-microdesc-consensus  cached-microdescs.new       state
/opt/home/admin # ls /opt/etc/tor
torrc
/opt/home/admin # ls /opt/etc/tor/torrc 
/opt/etc/tor/torrc
```

**Comment by blackcofee** [comment]
Зачем в torrc эта строка? 
Transport 10.5.0.1:9040
Уберите ее и пробуйте.

**Comment by Azat868** [comment]
Все заработало, огромное спасибо!
