### ISSUE TITLE
Списки заблокированных сайтов не полные.

### ISSUE THREAD

**Issue by khseal** [blackcofee/rublock-tor#3]
К примеру не проксируется заблокированный сайт zenrus.ru
А через впн антизапрета работает без проблем. Может есть источники где списки блокировок более полные?

**Comment by khseal** [comment]
Странно пользовался раньше этим впн https://antizapret.prostovpn.org/
Там сайты открывались, а тут их пришлось добавлять в ручную.

**Comment by blackcofee** [comment]
Ну скорее всего потому, что они выгружают туда все заблокированные подсети, а мы нет.

**Comment by khseal** [comment]
В целом ясно закрываю тогда вопрос. Спасибо за скрипт.
