### ISSUE TITLE
Уточнение в доке по скрипту

### ISSUE THREAD

**Issue by dammer** [blackcofee/rublock-tor#3]
При установке скриптом столкнулся, адрес LAN интерфейса в /opt/etc/tor/torrc
жестко прописан в 192.168.1.1, что не всегда истинно и соответственно без правки не заработает.
Думаю стоит упомянуть в доке, или выводе скрипта.

Автору спасибо, удобная штука

**Comment by blackcofee** [comment]
Сделал. Теперь он будет автоматически парситься.
