### ISSUE TITLE
Вопрос по настройке socks5

### ISSUE THREAD

**Issue by carloscondit** [blackcofee/rublock-tor#4]
Здравствуйте!
У меня в качестве интернет провайдера используется оператор сотовой связи МТС. В мой роутер xiaomi mi mini с прошивкой padavan подключен USB-модем Huawei e3372. На моем тарифном плане блокирована возможность скачивания торрентов. (ограничение скорости). Для обхода этой блокировки я использую Tor. В этом посте https://4pda.ru/forum/index.php?s=&showtopic=658537&view=findpost&p=41972397 на 4pda даны рекомендации по настройке. Подскажите, пожалуйста, можно ли как либо использовать SOCKS5-прокси из запущенного на роутере Tor, чтобы не запускать отдельный экземпляр Tor на компьютере? Я пробовал в настройках SOCKS5-прокси торрент-качалки указывать ip-адрес роутера, но это не работает. Может какое-то правило нужно прописать в правилах брандмауэра роутера? Заранее благодарен за помощь!

**Comment by blackcofee** [comment]
Приветствую. Для этого в конфиге тора нужно указать, а потом его перезапустить
`SocksPort 192.168.1.1:9050`
И после это уже вводить этот адрес в соответствующие поле, но качать торренты через тор не рекомендую, ибо убиваете этим всю их сеть, она для это не предназначена.

**Comment by carloscondit** [comment]
Понял. Спасибо за рекомендации. Я стараюсь пользоваться торрентами только в крайнем случае. Других способов скачивания их у меня пока нет.
Если я захочу еще телеграм бота установить на роутер, то для обхода блокировки телеграмма провайдером также нужно будет в скрипте бота указывать адрес сокс 192.168.1.1:9050?

**Comment by blackcofee** [comment]
Да, нужно будет указывать `192.168.1.1:9050`

**Comment by carloscondit** [comment]
Буду иметь ввиду. Еще раз спасибо за помощь!
