### ISSUE TITLE
Перестал учитывать conf-file

### ISSUE THREAD

**Issue by gizeasy** [blackcofee/rublock-tor#5]
Перестал учитываться conf-file=/opt/etc/rublock/rublock.dnsmasq
весь трафик стал идти через tor, 3 дня уже ковыряюсь, раз 10 все с нуля настраивал по интсрукции, подскажите пожалуйста что может быть не так?

у меня старый padavan где нельзя поставить dnscrypt-proxy2 стои dnscrypt-proxy
но сним все работало и где-то неделю назад я заметил что чтото сильно все тормозит

нормально работают только сервисы google: yotube drive и тп, и нормальная скорость у торентов

**Comment by blackcofee** [comment]
Проверил, все нормально работает. Весь трафик в принципе не может ходить через тор, ибо нужны правила которых тут нет.

**Comment by gizeasy** [comment]
если я иду https://yandex.ru/internet/, или на подобные сервисы
пишет что я не в России и скорость не выше 6ти мбит/сек

**Comment by blackcofee** [comment]
Видимо настраиваешь по инструкции для Украины, других предположений нет.

**Comment by gizeasy** [comment]
настраиваю так
https://github.com/blackcofee/rublock-tor/wiki/tor_ru

**Comment by gizeasy** [comment]
Алилуя!
И вы были правы)) проблема в настрйке rublock.sh был добавлен ресурс не верно
sed -i '$aipset=\/site.ru/\/rublock' rublock.dnsmasq - лишний слеш
sed -i '$aipset=\/site.ru\/rublock' rublock.dnsmasq

**Comment by blackcofee** [comment]
Он и сейчас неверно. Нужно `sed -i '$aipset=\/example.com\/rublock' rublock.dnsmasq`

**Comment by gizeasy** [comment]
при отправки экранирование отформатировалось, исправил
