### ISSUE TITLE
Не работает rublock.sh

### ISSUE THREAD

**Issue by DArk0711** [blackcofee/rublock-tor#6]
Скрипт rublock.sh выдаёт ошибку, роутер  RT-AC51U. Микропрограмма 3.4.3.9L-100_56960f9 от padavan

Parse register
List generation
**/opt/bin/lua: not enough memory**
Add more resources
Clear the list
Add ip to table
ipset v6.29: Element cannot be added to the set: it's already added
ipset v6.29: Element cannot be added to the set: it's already added
ipset v6.29: Element cannot be added to the set: it's already added
ipset v6.29: Element cannot be added to the set: it's already added
ipset v6.29: Element cannot be added to the set: it's already added
ipset v6.29: Element cannot be added to the set: it's already added
Restart dnsmasq

**Comment by DArk0711** [comment]
Видимо что-то с lua скриптом, может какое переполнение списка?

**Comment by blackcofee** [comment]
Нет, со скриптом все в порядке. Скорее всего из-за нехватки оперативки, по сути список парсится сначало туда в /tmp
