### ISSUE TITLE
Проблемы с ручной установкой

### ISSUE THREAD

**Issue by Blaktop** [blackcofee/rublock-tor#7]
Здравствуйте.
Пытаюсь установить блокиратор в ручном режиме, но на этапе "Открываем фаил start_script.sh для редактирования командой" я получаю сообщение: "**Cannot open /etc/storage/start_script.sh for reading**".  Поиск показывает, что такой файл не существует.

Также, в режиме автоустановки скрипта перед самой перезагрузкой роутера в терминале получаю такие команды:
**Add entries to dnsmasq
/tmp/install_tor.sh: line 87: can't create /etc/storage/dnsmasq/dnsmasq.conf: nonexistent directory
Add crontab tasks
/tmp/install_tor.sh: line 96: can't create /etc/storage/cron/crontabs/admin: nonexistent directory**

Роутер **ASUS** с прошивкой от **Мерлина** с установленной **Entware**.

**Comment by blackcofee** [comment]
Здравствуйте. Это только для прошивки от Padavan'a
