### ISSUE TITLE
Переадресация на другой сервер с TOR

### ISSUE THREAD

**Issue by GriefNorth** [blackcofee/rublock-tor#8]
Доброго времени, никак не могу ращобраться с переадресацией на другой сервер с тором, т.к. мой роутер локально его еле-еле переваривает и порой впадает в ступор.
Пытаюсь вот так.
```
iptables -t nat -I PREROUTING -i br-lan -p tcp -m set --match-set rublock dst -j DNAT --to-destination 192.168.1.2:9040
```

**Comment by blackcofee** [comment]
А в /etc/tor/torrc указан TransPort 192.168.1.2:9040 ?

**Comment by GriefNorth** [comment]
В dnsmasq.conf сервер изменил, имена из .onion резолвятся без проблем, конфиг тора на другом сервере 
```
User tor
DataDirectory /var/lib/tor
ExcludeExitNodes {RU},{UA},{AM},{KG}
StrictNodes 1
SocksPort 127.0.0.1:9050
SocksPort 192.168.1.2:9050
VirtualAddrNetwork 10.254.0.0/16
AutomapHostsOnResolve 1
TransPort 192.168.1.2:9040
TransPort 127.0.0.1:9040
DNSPort 127.0.0.1:9053
DNSPort 192.168.1.2:9053
```

**Comment by blackcofee** [comment]
Тут не все так просто, по сути tor создает socks-прокси, твое правило сработало бы с http-прокси. Надо поднимать прокси клиента на роутере (redsocks к примеру) и уже на его порт перенаправлять.
